[tool.briefcase]
project_name = "Scannify"
bundle = "com.example.scannify"
version = "0.0.1"
url = "https://scannify.example.com/scannify"
license = "BSD license"
author = 'Archer Simmons'
author_email = "Archer1799@gmail.com"

[tool.briefcase.app.scannify]
formal_name = "Scannify"
description = "Document scanner application"
icon = "src/scannify/resources/scannify"
sources = ['src/scannify']
requires = [
]


[tool.briefcase.app.scannify.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.scannify.linux]
requires = [
    'toga-gtk>=0.3.0.dev38',
]

[tool.briefcase.app.scannify.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.scannify.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.scannify.windows]
requires = [
    'toga-winforms>=0.3.0.dev38',
]

# Mobile deployments
[tool.briefcase.app.scannify.iOS]
requires = [
    'toga-iOS>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.scannify.android]
requires = [
    'toga-android>=0.3.0.dev38'
]

[tool.briefcase.app.scannify.web]
requires = [
    # Workaround; toga-web 0.3.0.dev38 doesn't include toga-core as a dependency.
    "toga-core>=0.3.0.dev38",
    "toga-web>=0.3.0.dev38",
]
style_framework = "Bootstrap v4.6"
